language: cpp
compiler: g++
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install g++-6 cmake qt5-default
  
script:
  - mkdir build
  - cd build
  - cmake -DINCLUDE_TESTS=ON ../
  - make -j$(nproc)
  - make test
  - cd bin/examples
  - ./CalculationTmu
  - ./BagModelFit 0.50 0.100 0.301 0.005
  - ./cpc1HRGTDep 0
  - ./cpc1HRGTDep 1
  - ./cpc1HRGTDep 2
  - ./cpc3chi2NEQ 0
  - ./cpc4mcHRG 1 100
  - ./PCE-Saha-LHC
  
